# this workflow will run on all pushes.
on:
  push:

name: "push"
jobs:
  # run golangci-lint to lint the golang source code.
  # the configuration is at /.golangci.yml.
  linter:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v6.0.3
      -
        name: Install mise
        uses: jdx/mise-action@v4
      -
        name: Lint
        run: mise run lint

  # use nancy to scan for vulnerabilities.
  vulnerability_scanner:
    name: Vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v6.0.3
      -
        name: Install mise
        uses: jdx/mise-action@v4
      -
        name: nancy
        run: go list -json -m all | docker run -i sonatypecommunity/nancy:latest

  # run golang test suite.
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v6.0.3
      -
        name: Install mise
        uses: jdx/mise-action@v4
      -
        name: Test
        run: mise run test

  # ensure the project builds successfully.
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v6.0.3
      -
        name: Install mise
        uses: jdx/mise-action@v4
      -
        name: Build
        run: mise run build

  # draft your next release notes as pull requests are merged into "master"
  # the configuration is at /.github/release-drafter.yml.
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@v7
        if: github.ref_name == github.event.repository.default_branch
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
